<a href="https://colab.research.google.com/github/hoin1357/BigDataPrograming_task/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a=np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [6]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [11]:
import numpy as np

unicode_array=np.array(['가나다','라마바','사아자'],dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [13]:
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [14]:
print(np.arange(2.0))
print(np.arange(2.0,6.5))

[0. 1.]
[2. 3. 4. 5. 6.]


In [16]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.linspace(2.0,3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [26]:
np.linspace(0.0,100.0,11,retstep=True)

(array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]),
 np.float64(10.0))

In [32]:
a=np.zeros(5)
a
b=np.zeros((2,1))
b

array([[0.],
       [0.]])

In [33]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [38]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [40]:
np.full([1,2,3,],(1,2,3))

array([[[1, 2, 3],
        [1, 2, 3]]])

In [42]:
np.full((2,2,3,),(1,2,3))

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [43]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.empty(7)

array([ 14.28571429,  28.57142857,  42.85714286,  57.14285714,
        71.42857143,  85.71428571, 100.        ])

In [55]:
a=np.arange(9).reshape(3,3)
print(a)
b= np.zeros_like(a)
print(b)
c=np.ones_like(a)
print(c)
d=np.full_like(a,5)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [57]:
a=np.arange(4)
a
print(a+2)
print(a*2)
print(a**2)
print(a%2)

[2 3 4 5]
[0 2 4 6]
[0 1 4 9]
[0 1 0 1]


In [60]:
a=np.arange(1,10).reshape(3,3)
a
b=np.full_like(a,[1,2,3])
print(a+b)
print(a*b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [62]:
a=np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [63]:
a.sum()

np.int64(46)

In [64]:
a.sum(axis=0)

array([16, 30])

In [65]:
a.sum(axis=1)

array([30, 13,  3])

In [66]:
a=np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [67]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [68]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [69]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [ ]:
import numpy as np
a=np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
print(a[8:2:-2])
print(a[-1:-7:-1])

[64 36 16]
[81 64 49 36 25 16]


In [ ]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
a[::-2]

array([81, 49, 25,  9,  1])

In [ ]:
a[2:5]=-100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
a[2:5]=[-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [ ]:
a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [ ]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [70]:
a[1:5:2]

array([[1, 2, 3]])

In [71]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [72]:
a[:,1]

array([5, 2])

In [74]:
a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [75]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [76]:
a[2,4]

np.int64(16)

In [77]:
a[2][4]

np.int64(16)

In [78]:
a[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [79]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [80]:
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [81]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [84]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [86]:
a[:-1,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [ ]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[[5]]

array([5])

3차원배열


In [87]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [89]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [90]:
a[:,1,1]

array([ 5, 17])

In [91]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [92]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [93]:
a[1,...,1]

array([13, 17, 21])

In [94]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [97]:
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [103]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [104]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [107]:
b=np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [115]:
lst=list(range(8))
print(lst)


[0, 1, 2, 3, 4, 5, 6, 7]


In [116]:
lst[3:5]=[30,40,50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [118]:
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [119]:
x[3:5]=[30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [120]:
x[3:5]=[30,40,50]

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [122]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
b=a
b is a

True

In [124]:
print(id(a))
print(id(b))

136662955652464
136662955652464


In [125]:
print(a.base)
print(b.base)

None
None


In [127]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [128]:
c=a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [129]:
print(id(a))
print(id(c))

136662955652464
136662955654192


In [130]:
c[0,0]=99
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [131]:
print(c.base)

None


In [132]:
v=a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [133]:
print(id(a))
print(id(v))

136662955652464
136662955646320


In [134]:
v[0,1]=200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [135]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [137]:
a=np.array([3,4,5])
b=np.array([8,7,6])
a+b

array([11, 11, 11])

In [138]:
a=np.array([3,4,5,7])
b=np.array([8,7,6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [139]:
from numpy import arange
x=arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
y=arange(-1,2)
y

array([-1,  0,  1])

In [141]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [142]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [143]:
x=arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
y=arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [145]:
np.set_printoptions(precision=2)

In [146]:
x/y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [147]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [148]:
x=arange(1,4)
x

array([1, 2, 3])

In [149]:
y=arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [150]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [151]:
x/y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [152]:
x=arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [153]:
y=arange(1,3)
y

array([1, 2])

In [154]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [155]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [160]:
import numpy as np
from numpy import array


x=array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [161]:
np.newaxis is None

True

In [164]:
a=x[None,:]
a

array([[ 0, 10, 20, 30]])

In [165]:
a=x[np.newaxis,:]
a

array([[ 0, 10, 20, 30]])

In [166]:
a=x[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [168]:
a.shape

(4, 1)

In [169]:
a=x[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [170]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [172]:
print(x[[2]])
print([[2,3]])

[2]
[[2, 3]]


In [173]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [175]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [176]:
from numpy import arange

x=arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [177]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [178]:
x[0,1]

np.int64(1)

In [179]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [180]:
x[,2:8]

SyntaxError: invalid syntax (1821174162.py, line 1)

In [181]:
x[[0],[1]]

array([1])

In [182]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [183]:
x[:,[5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [184]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [185]:
x[[1,3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [186]:
from numpy import arange
x=arange(56).reshape(7,8)
x


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [187]:
x[[1,3],[2,2]]

array([10, 26])

In [188]:
x[[1,3],[2]]

array([10, 26])

In [189]:
from numpy import arange

x=arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [190]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [191]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [192]:
x[array([0,2,4]),:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [193]:
from numpy import array
x[array([0,2,4]),array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [194]:
from numpy import arange
a=arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [195]:
a[2:4,3:7]
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [196]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [198]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [199]:
from numpy import arange
a=arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [200]:
a[arange(2,4)][:,[1,0]]

array([[17, 16],
       [25, 24]])

In [201]:
a[arange(2,5)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [202]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [203]:
a[arange(2,5)][:,arange(-1,8,-1)]

array([], shape=(3, 0), dtype=int64)